#!/usr/bin/env swift

// Regenerates the embedded-asset translation units in Sources/TabulaSonoraBridge from the
// submodule's assets/*.json.
//
// The CMake build does this at configure time via cmake/EmbedAsset.cmake, so a SwiftPM build --
// which has no configure step -- has to produce the same translation units some other way. This
// script emits byte-for-byte equivalent ones, and records each input's SHA-256 in the header so a
// stale copy is visible rather than silently wrong.
//
// Run it whenever the submodule moves:
//
//     swift Packages/TabulaSonoraKit/Scripts/embed-assets.swift

import Foundation
import CryptoKit

/// One `ts_embed_asset()` call from src/CMakeLists.txt, restated.
///
/// The symbol is what `rom/embedded_assets.hpp` declares and the engine calls; CMake derives the
/// generated file's name from it, so these have to agree with the C++ side rather than with the
/// input's file name.
struct Asset {
    let input: String
    let symbol: String
    /// Why a stale copy matters, said in the generated file where someone editing it will read it.
    let staleWarning: String
}

let assets = [
    Asset(input: "manifest.json",
          symbol: "manifest_json",
          staleWarning: "the engine parses this at first use and a stale map points at the wrong "
              + "table offsets"),
    Asset(input: "builds.json",
          symbol: "builds_json",
          staleWarning: "it is the list of SCCore.dll builds the engine will accept, and the "
              + "offset translation for each, so a stale copy refuses files it can read"),
]

let scriptURL = URL(fileURLWithPath: CommandLine.arguments[0]).resolvingSymlinksInPath()
let packageRoot = scriptURL.deletingLastPathComponent().deletingLastPathComponent()

for asset in assets {
    let input = packageRoot.appendingPathComponent("nativets/assets/\(asset.input)")
    let output = packageRoot.appendingPathComponent(
        "Sources/TabulaSonoraBridge/\(asset.symbol).generated.cpp")

    guard let data = try? Data(contentsOf: input) else {
        FileHandle.standardError.write(
            "embed-assets: cannot read \(input.path)\n".data(using: .utf8)!)
        FileHandle.standardError.write(
            "Is the nativets submodule checked out? git submodule update --init\n".data(using: .utf8)!)
        exit(1)
    }

    let digest = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()

    // Sixteen bytes to a line, matching EmbedAsset.cmake's chunking, so a diff against a CMake-built
    // tree is empty rather than reflowed.
    var body = ""
    for (index, byte) in data.enumerated() {
        if index % 16 == 0 { body += index == 0 ? "    " : "\n    " }
        body += String(format: "0x%02x,", byte)
    }

    let source = """
    // Generated by Scripts/embed-assets.swift from assets/\(asset.input). Do not edit.
    //
    // Source SHA-256: \(digest)
    // Source length:  \(data.count) bytes
    //
    // This is the CMake build's ts_embed_asset() output, hand-rolled for SwiftPM. If the
    // submodule's \(asset.input) changes, rerun the script -- \(asset.staleWarning).
    #include "rom/embedded_assets.hpp"

    namespace ts::assets {

    namespace {
    constexpr unsigned char k_\(asset.symbol)_bytes[] = {
    \(body)
    };
    } // namespace

    std::string_view \(asset.symbol)() noexcept
    {
        return std::string_view(reinterpret_cast<const char*>(k_\(asset.symbol)_bytes), \(data.count));
    }

    } // namespace ts::assets

    """

    try! FileManager.default.createDirectory(
        at: output.deletingLastPathComponent(), withIntermediateDirectories: true)
    try! source.write(to: output, atomically: true, encoding: .utf8)

    print("embed-assets: \(asset.input) — \(data.count) bytes -> \(output.lastPathComponent)")
    print("embed-assets: \(asset.input) — sha256 \(digest)")
}
