#!/usr/bin/env swift

// Regenerates Sources/TabulaSonoraBridge/manifest_json.generated.cpp from the submodule's
// assets/manifest.json.
//
// The CMake build does this at configure time via cmake/EmbedAsset.cmake, so a SwiftPM build --
// which has no configure step -- has to produce the same translation unit some other way. This
// script emits a byte-for-byte equivalent one, and records the input's SHA-256 in the header so a
// stale copy is visible rather than silently wrong.
//
// Run it whenever the submodule moves:
//
//     swift Packages/TabulaSonoraKit/Scripts/embed-manifest.swift

import Foundation
import CryptoKit

let scriptURL = URL(fileURLWithPath: CommandLine.arguments[0]).resolvingSymlinksInPath()
let packageRoot = scriptURL.deletingLastPathComponent().deletingLastPathComponent()

let input = packageRoot.appendingPathComponent("nativets/assets/manifest.json")
let output = packageRoot.appendingPathComponent(
    "Sources/TabulaSonoraBridge/manifest_json.generated.cpp")

guard let data = try? Data(contentsOf: input) else {
    FileHandle.standardError.write(
        "embed-manifest: cannot read \(input.path)\n".data(using: .utf8)!)
    FileHandle.standardError.write(
        "Is the nativets submodule checked out? git submodule update --init\n".data(using: .utf8)!)
    exit(1)
}

let digest = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()

// Sixteen bytes to a line, matching EmbedAsset.cmake's chunking, so a diff against a CMake-built
// tree is empty rather than reflowed.
var body = ""
for (index, byte) in data.enumerated() {
    if index % 16 == 0 { body += index == 0 ? "    " : "\n    " }
    body += String(format: "0x%02x,", byte)
}

let source = """
// Generated by Scripts/embed-manifest.swift from assets/manifest.json. Do not edit.
//
// Source SHA-256: \(digest)
// Source length:  \(data.count) bytes
//
// This is the CMake build's ts_embed_asset() output, hand-rolled for SwiftPM. If the submodule's
// manifest.json changes, rerun the script -- the engine parses this at first use and a stale map
// points at the wrong table offsets.
#include "rom/embedded_assets.hpp"

namespace ts::assets {

namespace {
constexpr unsigned char k_manifest_json_bytes[] = {
\(body)
};
} // namespace

std::string_view manifest_json() noexcept
{
    return std::string_view(reinterpret_cast<const char*>(k_manifest_json_bytes), \(data.count));
}

} // namespace ts::assets

"""

try! FileManager.default.createDirectory(
    at: output.deletingLastPathComponent(), withIntermediateDirectories: true)
try! source.write(to: output, atomically: true, encoding: .utf8)

print("embed-manifest: \(data.count) bytes -> \(output.lastPathComponent)")
print("embed-manifest: sha256 \(digest)")
